# Generated by Django 5.2.6 on 2026-03-28 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('athlete_name', models.CharField(blank=True, default='', max_length=255)),
                ('goal', models.CharField(blank=True, default='', max_length=255)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('published', 'Published')], default='published', max_length=20)),
                ('builder_data', models.JSONField(default=dict, help_text='Full ProgramBuilderSnapshot from frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='authentication.user')),
            ],
            options={
                'db_table': 'programs_program',
                'ordering': ['-updated_at'],
            },
        ),
    ]
