# Generated by Django 5.2.6 on 2026-03-28 16:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CREATED', 'Created'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_volume', models.FloatField(default=0.0, help_text='Auto-calculated sum of all sets (weight * reps)')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='authentication.user')),
            ],
            options={
                'db_table': 'programs_training_session',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=255)),
                ('set_number', models.PositiveIntegerField()),
                ('weight', models.FloatField(default=0.0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('rpe', models.FloatField(blank=True, null=True)),
                ('is_pr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='programs.trainingsession')),
            ],
            options={
                'db_table': 'programs_set_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sleep_quality', models.PositiveIntegerField(help_text='1-10 scale')),
                ('soreness', models.PositiveIntegerField(help_text='1-10 scale')),
                ('stress', models.PositiveIntegerField(help_text='1-10 scale')),
                ('energy', models.PositiveIntegerField(help_text='1-10 scale')),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_logs', to='authentication.user')),
            ],
            options={
                'db_table': 'programs_daily_readiness',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
