# Generated by Django 5.2.6 on 2026-03-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='notes',
        ),
    ]
