# Generated by Django 5.2.6 on 2026-03-28 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('COMPOUND', 'Compound'), ('ISOLATION', 'Isolation'), ('ACCESSORY', 'Accessory'), ('CARDIO', 'Cardio'), ('MOBILITY', 'Mobility')], default='COMPOUND', max_length=20)),
                ('primary_muscle', models.CharField(db_index=True, max_length=100)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(choices=[('BARBELL', 'Barbell'), ('DUMBBELL', 'Dumbbell'), ('KETTLEBELL', 'Kettlebell'), ('MACHINE', 'Machine'), ('CABLE', 'Cable'), ('BODYWEIGHT', 'Bodyweight'), ('BANDS', 'Bands'), ('OTHER', 'Other')], default='BARBELL', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, help_text='Link to a demo video', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Link to a movement diagram', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercises_exercise',
                'ordering': ['name'],
            },
        ),
    ]
